version: 1.2
workflows:
 - name: TheiaEuk_PE
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_theiaeuk_pe.wdl
   testParameterFiles:
    - empty.json
 - name: Cauris_CladeTyper
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_cauris_cladetyper.wdl
   testParameterFiles:
    - empty.json
 - name: Snippy_Variants
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_snippy_variants.wdl
   testParameterFiles:
    - empty.json
 - name: Snippy_Tree
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_snippy_tree.wdl
   testParameterFiles:
    - empty.json
 - name: Nullarbor
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_nullarbor.wdl
   testParameterFiles:
    - empty.json
 - name: Lyve_SET
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_lyveset.wdl
   testParameterFiles:
    - empty.json